In [2]:
import pandas as pd
import random

# Define months and operators
months = ['Jan', 'Feb', 'Mar']
operators = ['Operator A', 'Operator B']

# Initialize an empty list to store the data
data = []

# Generate data for each month and operator
for month in months:
    for operator in operators:
        # Generate random data for each KPI
        cycle_time = random.randint(40, 50)
        throughput = random.randint(500, 650)
        utilization_rate = random.uniform(75, 90)
        mtbf = random.randint(170, 230)
        mttr = random.uniform(1.5, 2.5)
        planned_downtime = random.randint(10, 25)
        unplanned_downtime = random.randint(5, 12)
        scrap_rate = random.uniform(2, 3.5)
        rework_rate = random.uniform(1, 2.5)
        first_pass_yield = 100 - scrap_rate - rework_rate
        acknowledgment_time = random.randint(4, 8)
        resolution_time = random.randint(20, 35)
        escalation_time = random.randint(12, 20)
        
        # Append data to the list
        data.append([month, operator, cycle_time, throughput, utilization_rate,
                     mtbf, mttr, planned_downtime, unplanned_downtime,
                     scrap_rate, rework_rate, first_pass_yield,
                     acknowledgment_time, resolution_time, escalation_time])

# Create a DataFrame from the list of data
df = pd.DataFrame(data, columns=['Month', 'Operator', 'Cycle Time (mins)', 'Throughput (units)', 'Utilization Rate (%)',
                                 'MTBF (hours)', 'MTTR (hours)', 'Planned Downtime (hours)', 'Unplanned Downtime (hours)',
                                 'Scrap Rate (%)', 'Rework Rate (%)', 'First-pass Yield (%)',
                                 'Acknowledgment Time (mins)', 'Resolution Time (mins)', 'Escalation Time (mins)'])

# Display the DataFrame
df

,Month,Operator,Cycle Time (mins),Throughput (units),Utilization Rate (%),MTBF (hours),MTTR (hours),Planned Downtime (hours),Unplanned Downtime (hours),Scrap Rate (%),Rework Rate (%),First-pass Yield (%),Acknowledgment Time (mins),Resolution Time (mins),Escalation Time (mins)
0,Jan,Operator A,40,642,88.380679,218,2.009330,13,7,2.873814,1.099707,96.026478,6,31,14
1,Jan,Operator B,48,627,79.780436,190,2.386806,18,6,3.465091,2.157503,94.377406,5,24,18
2,Feb,Operator A,46,577,81.622792,208,1.739973,11,8,3.059503,1.623285,95.317212,4,31,13
3,Feb,Operator B,41,569,78.406781,207,2.076914,15,10,3.150116,1.591370,95.258515,6,32,20
4,Mar,Operator A,41,583,76.677766,195,1.624292,11,9,2.624498,1.592107,95.783395,7,30,18
5,Mar,Operator B,45,572,87.549133,171,2.294700,21,12,2.116535,2.344344,95.539121,7,24,18